#!/bin/bash
cd src/parser
jjtree CFlow.jjt
javacc CFlow.jj
cd ../..

if [ ! -d "bin" ]
then
    mkdir bin
fi
rm -Rf bin/*

javac $(find ./src/* | grep .java) -d bin/
java -cp bin/ parser.CFlow ${@:1}
