#!/bin/bash
cd src/parser
jjtree CFlow.jjt
javacc CFlow.jj
cd ../..

if [ ! -d "bin" ]
then
    mkdir bin
fi
rm -Rf bin/*

javac -cp ".:lib/gs-core-1.3/gs-core-1.3.jar:lib/gs-ui-1.3/gs-ui-1.3.jar" $(find ./src/* | grep .java) -d bin/
java -cp ".:lib/gs-core-1.3/gs-core-1.3.jar:lib/gs-ui-1.3/gs-ui-1.3.jar:bin/" parser.CFlow ${@:1}