/* Generated By:JavaCC: Do not edit this line. CFlowTreeConstants.java Version 5.0 */
package parser;

public interface CFlowTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTUNION = 1;
  public int JJTVOID = 2;
  public int JJTCONCAT = 3;
  public int JJTREPEAT = 4;
  public int JJTCHAR = 5;
  public int JJTPOSITIVESET = 6;
  public int JJTNEGATIVESET = 7;
  public int JJTRANGE = 8;


  public String[] jjtNodeName = {
    "Expression",
    "Union",
    "void",
    "Concat",
    "Repeat",
    "Char",
    "PositiveSet",
    "NegativeSet",
    "Range",
  };
}
/* JavaCC - OriginalChecksum=e42482cb66c65241785cffda88c34819 (do not edit this line) */
